### ISSUE TITLE
Incompatible with OC 8.0.3

### ISSUE THREAD

**Issue by wurstchristoph** [owncloud/notes#105]
This app is incompatible with the current OC stable release (8.0.3):

![](https://cloud.githubusercontent.com/assets/1374172/7552187/d89ebb8a-f6a6-11e4-855a-50580bcd58bf.png)
![](https://cloud.githubusercontent.com/assets/1374172/7552188/d8a28fee-f6a6-11e4-843a-bc5c2548fa24.png)

ref #104

**Comment by ctgcwiqc** [comment]
Confirmed issue.  Installed via git on OC 8.0.3.  Unable to enable as app requires OC 8.1???  8.0.3 is the latest stable release, no?

**Comment by Raydiation** [comment]
Use an older release then, check the releases page

**Comment by Raydiation** [comment]
;)

**Comment by ctgcwiqc** [comment]
Im new to this type of stuff.  I jsut figured out today what github is actually for.  Kudos on having the app ready for the next OC release.  There are several apps that are no longer maintained.

**Comment by wurstchristoph** [comment]
Ah, now I get it. I misread it (currently supported version is 8.1 not 8.0.1) :see_no_evil:

**Comment by ctgcwiqc** [comment]
So is there a way to download the older releases with "git clone" or does it have to be done with "wget https://github.com/owncloud/notes/archive/1.0.0.zip".  I am a rookie so be kind.  I have already installed the zip using wget, but if there is a way so that I dont have to download, extract, rename extracted, delete zip then I would prefer that.

**Comment by Raydiation** [comment]
You can just use your git clone repo and run:

    git checkout tags/1.0.0
