### ISSUE TITLE
Support for non txt extension

### ISSUE THREAD

**Issue by gerroon** [owncloud/notes#111]
Hi

It would be great if non txt extensions are supported. I sync my org (.org) files to the folder but I cant see them in the Notes apps. So it would be great if the extensions is customizable.

**Comment by tapir** [comment]
:+1:  for this. I'm using .note files which is used by Tomboy and GNOME Notes.

**Comment by Henni** [comment]
I think we should limit the allowed file extensions.
Instead of trying to handle every file (including images) which are placed in the notes folder only the following extensions will be accepted:

- .txt
- .md
- .note
- [.org - I'm not sure about this one as it's mostly used as a music file extension]

feel free to extend this list!
cc @jancborchardt

**Comment by grefel** [comment]
* .markdown

**Comment by pierrejochem** [comment]
@Henni: :+1:  (.txt, .md + .note)

**Comment by gerroon** [comment]
.org mode is an emacs extension not a music file extension

**Comment by jancborchardt** [comment]
Yeah, .org is Emacs. Music is .ogg ;)
