### ISSUE TITLE
How to detect notes app on server?

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/notes#221]
How can the notes app be detected on server via the REST-API?
Is the preferred method to just do a REST-call and see if it returns a Status 200 or should there be a own API maybe?

**Comment by Henni** [comment]
I think just sending a REST request is the best way. Everything else would have to be implemented in core.

**Comment by korelstar** [comment]
One addition for people writing clients using this approach: checking the HTTP status 200 is **not** sufficient, since ownCloud may display an error message or the login page and use nevertheless HTTP status 200, if the notes app is not installed on the server. So at least, you have to check if the server's response (e.g. on `/index.php/apps/notes/api/v0.2/notes`) is valid JSON.
