### ISSUE TITLE
ownnote and note - different applications? - note broken after reinstall - OC 9, Linux

### ISSUE THREAD

**Issue by wgregori** [owncloud/notes#233]
I installed ownnote via my oc apps web page and it worked fine.  Next, I installed ownnote on an android phone and it worked... however, when trying to setup ownnote for iOS it failed referencing that is could not find the app "note".  

Seeing that there was not directory called note but one called ownnote - I uninstalled ownnote, deleted the ownnote directory and then used the OC web interface to install Note.  The installation created a directory called "note"... but the installation was broken - When trying to access it via the web interface all my previous notes were gone and I was unable to create any new notes.  

Now I'm stuck-  trying to get back to a working Note installation.  questions

1. are there two applications ownnote and note?
2. Which is the more mature - likely to continue?
3.  How do I get back to a working installation.

I'm using OC 9 - on Raspbien Linux
Thanks
Wayne

**Comment by cengbrecht** [comment]
This is something I'd also like to know.

**Comment by Henni** [comment]
1. Yes there are two applications
2. They are currently coexisting and have different goals. Notes is minimalistic, while OwnNote offeres a WYSIWYG editor
3. I guess your broken installation is fixed by now. But to actually solve this I'd need a bit more information on what is broken.

I'll close this issue for now. Please reopen if you still need help with fixing your installation
