### ISSUE TITLE
Introduce a save button and save only automatically on note change

### ISSUE THREAD

**Issue by godfuture** [owncloud/notes#52]
I think it is pretty confusing that no save button exists for several reasons:
- since there no notifications when the notes gets saved, the user is uncertain about their persistence
- what does the user have to do to trigger a save?
- how does the user notice that the note is not saved yet? (In many text editors the save button just greys out since there are no changes. When changes were done, the save is back in game)

**Comment by Raydiation** [comment]
fixed

**Comment by jancborchardt** [comment]
@Raydiation maybe even better, how about having the window close be blocked, but only when a save is in progress? Like with a browser-side modal.

That would be a bit more elegant and properly catch the edge-case, instead of showing an annoying »Saving« indicator often.

**Comment by Raydiation** [comment]
Should be in addition to this since otherwise there is no feedback for you when you are able to close the window. Can you open a new issue?

**Comment by jancborchardt** [comment]
Since saving is probably very fast, you’ll be able to close the window almost anytime. Wanting to close the window _immediately_ after editing something is probably rarer than doing it 500ms later.

It’s not an addition I think, for that reason. It’s the correct solution, instead of showing a »Saving« notice which isn’t really needed as we didn’t have it before. It doesn’t make clear that you shouldn’t close the window.

**Comment by Raydiation** [comment]
Well I'm more concerned about network timeouts, especially on mobile
